---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  session_secret: ODE1NWIyODgwOWQ2MGJlMDQxNjM4N2E5OWM5NDI5NzU=
  token_secret: MTQyNGU2ZjBhMTQ2MzM5Yjc0YWYyNzlkNjRhOTIzNjI=
  email_id: dGVzdGluZy5vbkBtZS5jb20=
  email_auth: bm90YXNlY3JldA==
  instance_name_secret: N2Q2YzllOGY2ODcwZWZhNGU1YmJiYzU3YjdiY2JmZDM=
  db_host: ZGF0YWJhc2Utc3Zj
  db_user: cG9zdGdyZXM=
  db_password: TXlmb290c3Ryb25ncGFzc3dkMDQzLgo=
  db_name: cG9zdGdyZXM=
